http/http_rest_proxy.cc, http/http_rest_proxy.h, soa/service/aws.h, soa/service/s3.cc, soa/service/s3.h, utils/json_utils.h
Simple one: we don't expose the CurlWrapper so that the HttpRestProxy can be part of our API without pulling too many extra dependencies.
=> Don't expose CurlWrapper in HttpRestProxy (MLDB-1200)

types/id.cc, types/id.h, types/jml_serialization.h, types/testing/id_test.cc, utils/json_utils.h
This hoists the non-standard type (which is also not available on 32 bit machines or some compilers) out of the header files, and into implementation files.
=> Removed __int128_t from interface (MLDB-1201)

plugins/svd.cc
Looks like sometimes the SVD will return less columns than we asked for, but we calculated our loop bounds based upon what we asked for not what we got.  This should fix a potential out-of-bounds.
@mailletf please verify the fix.
=> Fixed out of bounds D value (MLDB-1202)

plugins/csv_dataset.cc, testing/MLDB-1212_csv_import_long_quoted_lines.py, testing/testing.mk
Fixes issues with parsing quoted CSV fields longer than 4096 bytes.
@mailletf FYI
=> MLDB-1212 csv import long quoted lines

plugins/classifier.cc, plugins/csv_dataset.cc, plugins/lang/js/mldb_js.cc, plugins/lang/python/callback.h, plugins/lang/python/python_converters.cc, plugins/lang/python/python_plugin_context.cc, plugins/nlp.cc, plugins/sentiwordnet.cc, plugins/sql_functions.cc, plugins/sql_functions.h, plugins/tsne.cc, plugins/word2vec.cc, plugins/xlsx_importer.cc, server/mldb_server.cc, server/script_output.h, soa/service/archive.cc, soa/service/async_event_source.cc, sql/builtin_functions.cc, sql/cell_value.cc, types/date.cc, types/date.h, types/testing/periodic_utils_test.cc, types/testing/value_description_test.cc, vfs/filter_streams.h, vfs/fs_utils.cc, vfs/fs_utils.h
Another simple change: value_description.h and parse_context.h were removed from the #includes for the Date class, and everything that broke was fixed.  Decouples the interfaces from the implementation and reduces compile times.
=> Removed Parse_Context include from Date class (MLDB-1215)

soa/service/archive.cc, soa/service/docker.cc, soa/service/s3.cc, soa/service/sftp.cc, soa/service/sftp.h, vfs/filter_streams.cc, vfs/filter_streams.h, vfs/fs_utils.cc, vfs/http_streambuf.cc, vfs/testing/filter_streams_test.cc
Provides access to information and metadata (etag, permissions, size, etc) that is already known for most implementations without requiring a separate, non-atomic call to getUriObjectInfo.
=> filter_stream can return object info (MLDB-1218)

arch/arch.mk, arch/spinlock.cc, arch/spinlock.h
This replaces #33 with a simpler implementation.  There were external plugins that were using the exposed try_lock() method, so it's been added back in.
=> Added back in try_lock to spinlock (MLDB-1218)

types/json_parsing.h, types/json_printing.cc, types/testing/json_handling_test.cc
@wsourdeau FYI.  The MLDB versions are a little different and we took the opportunity to avoid making a character by character copy of the string passed in if it doesn't need escaping.
=> Don't stack overflow on JSON encoding long strings (MLDB-1238)

vfs/http_streambuf.cc
Fixes Valgrind failures when loading files from http.
=> Fixed use-after-free in HTTP headers (MLDB-1218)

container_files/assets/www/doc/builtin/functions/Tfidf.md, ml/kmeans.h, plugins/classifier.cc, plugins/kmeans.cc, plugins/kmeans.h, plugins/tfidf.cc, plugins/tfidf.h, testing/MLDB-1025-output-dataset-serialization-test.cc, testing/MLDB-1101-tf-idf.py, testing/MLDB-285-kmeans-function.js, testing/MLDB-926_auto_functions_for_procs.py
- modified the kmeans procedure to persist the centroids as a model file - that model is necessary to create a kmeans function
- similarly modified tf-idf procedure to persist the document frequencies of the terms in the corpus along with the corpus size - that model is also necessary when creating a kmeans function
- adapted and augmented the test coverage of the kmeans and tf-idf functions
=> Mldb 1226 persist model

container_files/init/mldb_finish.py, container_files/init/mldb_logger.py, container_files/init/mldb_runner.sh, container_files/template_vars.mk, release.mk
The docker init system (based on runsvdir) will call
/etc/service/mldb_runner/finish when mldb_runner exits.
The finish script will print a message with the signal number that killed the
process if it is available.
The 'run' script has been tweaked to 'exec' mldb_runner instead of forking it.
This is required for the finish script to properly get the signal code when
mldb_runner exits.
Since we now 'exec', we cannot use a pipeline to redirect stderr to stdout and
stdout to tee.  Instead, we use a logging script, which is a simple wrapper
around tee. runsv will arrange to wire up the file descriptor correctly
(mldb_runner's stdout to the logger's stdin).
=> MLDB-1244 Add 'finish' and logging script to mldb service

container_files/init/credentialsd_runner.sh, container_files/init/ipython_notebook_runner.sh, container_files/init/nginx_runner.sh, container_files/init/uwsgi_validator_runner.sh
Allows all services to be properly controlled by sv {status,start,stop} service
The in-container log file for all services will not be generated anymore.
If we ever need those, we can use a 'log' script like mldb_runner does.
=> Update services to use 'exec' and drop tee -a log

rest/poly_collection.cc, rest/poly_collection.h, rest/poly_collection_impl.h, rest/rest_collection.cc, rest/rest_collection.h, rest/rest_collection_impl.h, rest/testing/rest_collection_test.cc
It occurrs when the object is destroyed before threads have finished
running. I added a counter and a condition variable to have the dtor
wait for them before dtoring.
=> Fix a segfault in rest_collection

plugins/bucketize_procedure.cc, plugins/csv_dataset.cc, testing/MLDB-1043-bucketize-procedure.js
Causes the latest timestamp for the order by column to be used by the bucketize procedure.
Also fixes a bug in CSV timestamps that caused the test to fail originally.
@FinchPowers FYI
=> MLDB-1267 bucketize latest timestamp

server/bound_queries.cc
Fix (for now) a small issue where some rows could report a bucket index == bucketnumber.
=> MLDB-1233 small fix for bucket number in group by

builtin/filtered_dataset.cc, builtin/filtered_dataset.h, builtin/joined_dataset.cc, builtin/joined_dataset.h, core/dataset.cc, core/dataset.h, plugins/embedding.cc, plugins/embedding.h, server/dataset_context.cc, server/forwarded_dataset.cc, server/forwarded_dataset.h, sql/join_utils.cc, sql/join_utils.h, sql/sql_expression.h, sql/table_expression_operations.cc, testing/MLDB-180-basic-join.js
This fixes calling dataset.rowName() in 3 way joins by allowing the joinDataset to override the getFunction with the table name in order to check what was the original rowName from that dataset in the joined row.
Does *not* fix it for N-way joins yet, that will be next, I want to pull this to unblock some users.
=> Mldb 12550 3 way outer join

builtin/joined_dataset.cc, core/dataset.cc, sql/execution_pipeline_impl.cc, sql/execution_pipeline_impl.h, sql/sql_expression.h, sql/sql_expression_operations.cc, sql/table_expression_operations.cc
Interface cleanup that's necessary for correlated subqueries and row-table expressions.
Test for MLDB-1273 was already failing on master; it's not a new failure.
=> Added RowScope to basic row generators (MLDB-1315)

sql/binding_contexts.h, sql/builtin_dataset_functions.cc, sql/sql_expression.cc, sql/sql_expression.h, sql/sql_expression_operations.cc, sql/sql_expression_operations.h, sql/table_expression_operations.cc
- Improves the scope of SqlExpression::constantValue() allowing for it to be used in more situations
- Better error messages
- Improved accuracy in isConstant()
- Make function binding exception safer
=> Small cleanups in sql expression ops (MLDB-1321)

container_files/assets/www/doc/builtin/lang/Javascript.md, container_files/assets/www/doc/builtin/sql/TypeSystem.md, container_files/assets/www/doc/builtin/sql/ValueExpression.md, core/function.cc, core/function.h, http/http_exception.h, jml/utils/utils.mk, plugins/lang/js/js_common.cc, plugins/lang/js/mldb_js.cc, plugins/lang/js/mldb_js.h, soa/service/s3.cc, soa/service/service.mk, sql/builtin_functions.cc, sql/cell_value.cc, sql/cell_value.h, sql/cell_value_impl.h, sql/expression_value.cc, sql/expression_value.h, sql/sql.mk, sql/sql_expression.h, sql/sql_expression_operations.cc, testing/MLDB-1213-blob-support.js, testing/cell_value_test.cc, testing/testing.mk, types/string.h, utils/hash.cc, utils/hash.h, utils/utils.mk
This adds basic support for binary blobs in the SQL query cells, as well as functions in
Javascript to manipulate them, facilities for encoding and decoding in base64,
documentation and basic tests.
As part of the change, some of the old JML hash functionality was moved into MLDB
proper.
=> Added BLOB cell value (MLDB-1213)

mldb_macros.mk
To run all the tests (as before)
```
make -j28 MLDB-1155_csv_line_endings.py
```
To run a single test (new)
```
make -j28 MLDB-1155_csv_line_endings.py MLDB-1155_csv_line_endings.py_ARGS="'[\"CsvLineEndingsCsvGz.test_empty_csv\"]'"
```
=> Allows usage of make x x_ARGS for mldb_unit_test

container_files/init/mldb_finish.py
- Use constant instead of magic number
- Let the operator know mldb that the container is being shut down
=> Cosmetic changes to graceful shutdown code

mldb_base/docker_create_mldb_base.sh
- Update mirrors url to use ec2
- use lib{blas,lapack}3 instead of the gf transitional pkg
- get rebuild_pycs.py through mldb/ symlink
=> mldb_base tweaks

core/function.cc, core/function.h, plugins/sql_functions.cc, plugins/sql_functions.h, server/function_collection.cc, server/function_contexts.cc, server/function_contexts.h, server/serial_function.cc, server/sql_expression_function_operations.cc, sql/binding_contexts.cc
The only things that FunctionExpressionContext now makes available are:
-The input values
-Functions (from the server)
-Function stack depth for recursion detection
=> MLDB-1307 FunctionExpressionContext is no longer readthrough

server/dataset_context.cc, server/dataset_context.h, server/function_contexts.cc, sql/sql_expression.cc, sql/sql_expression.h, sql/sql_expression_operations.cc, testing/MLDB-835-table-aliases.py, testing/MLDB-869-select-expression.py
If you take SELECT x.*
instead of assuming it means all column from dataset x, we will wait until binding to see if it means that or all columns that starts with "x."
Add a new method to the SqlBindingScope interface to resolve table names in identifier.
=> MLDB-1313 delay resolution of wildcard ambiguity from parsing to binding

sql/builtin_functions.cc, sql/expression_value.cc, sql/expression_value.h, testing/MLDB-1336-builtin-checks.py, testing/testing.mk
Note that the exception thrown should not specify the function name as it will be added when the exception is caught lower in the call stack.
=> Mldb 1336 Better error message for function arguments

sql/expression_value.cc, sql/expression_value.h, testing/sql_expression_test.cc
Removes some useless padding in the ExpressionValue class, which should reduce overall memory usage somewhat in queries.
Very trivial.
=> Reduced ExpressionValue useless padding (MLDB-1363)

server/mldb_server.cc, server/mldb_server.h
Workaround for the issue that @mailletf encountered when calling date_part in MT
=> MLDB-1362 workaround for boost::date_time MT issue

server/bound_queries.cc
It now works like the other cases. Fixes segfault in some case where the last bucket would start out of bound.
=> Fix incorrect number of row to treat per bucket

container_files/assets/www/doc/builtin/Running.md, core/dataset.cc
Adds an option (enabled by default) to return memory to the OS by unmapping unused page ranges from tcmalloc.
=> Allow memory to be returned to OS (MLDBFB-329)

container_files/assets/www/doc/builtin/procedures/InputQuery.md, server/static_content_macro.cc, types/value_description.cc
Fixes documentation error messages.  Looks like the root cause was that the typeName field of ValueDescription was inadvertently changed from the demangled to the non-demangled form.
Also adds a missing documentation block to the InputQuery, which is enabled by this change.
=> Fixed type names not being found by demangled lookup (MLDB-1392)

plugins/experiment_procedure.cc, server/static_content_handler.cc, server/static_content_macro.cc, server/static_content_macro.h
Slight refactoring of MD support to allow for the field descriptions to be rendered in Markdown.
=> Allow MD in comment fields for structures (MLDB-1261)

plugins/for_each_line.cc, testing/MLDB-749-csv-dataset.js
Removes the exit with std::terminate when an error occurs in CSV parsing from a worker thread.
=> Fixed termination in CSV loading exception (MLDB-1404)

container_files/assets/www/doc/builtin/plugins/SharedLibrary.md, core/plugin.cc, core/plugin.h, testing/MLDB-1398-plugin-library-dependency.js, testing/MLDB-1398-plugin/MLDB-1398-dep-library.cc, testing/MLDB-1398-plugin/MLDB-1398-main-library.cc, testing/MLDB-1398-plugin/MLDB-1398-plugin.mk, testing/MLDB-1398-plugin/mldb_plugin.json, testing/testing.mk
This test-case was implemented to reproduce an issue in plugin loading.  In the end, the issue wasn't reproducible, but we should keep the test-case to ensure there isn't a regression.
This only changes tests.
=> Added test-case for plugin implemented in multiple libraries (MLDB-1398)

Building.md, base/testing/thread_pool_test.cc, core/dataset.cc, ext/tensorflow.mk, jml-build/clang.mk, jml-build/gcc.mk, jml-build/gcc5.mk, ml/algebra/least_squares.h, ml/jml/classifier.h, ml/jml/stump.cc, ml/jml/testing/boosting_testing.mk, ml/jml/testing/weighted_training_test.cc, ml/jml/training_index_entry.cc, ml/svd_utils.cc, server/bound_queries.cc, sql/binding_contexts.cc, sql/builtin_aggregators.cc, sql/builtin_functions.cc, sql/cell_value.cc, sql/coord.cc, sql/execution_pipeline_impl.cc, sql/expression_value.cc, sql/expression_value.h, sql/sql_expression_operations.cc, sql/tokenize.h, testing/MLDB-1190_segfault_sqlexpr_jseval.py, testing/mldb_determinism_test.cc, types/any.cc, types/url.cc
Fixes the warnings that come from the other compilers and make MLDB compile with any of them.  It found some consequential bugs including those in MLDB-1409, MLDB-1410 and that in binding_contexts.cc.
=> Compile with clang, gcc5 (MLDB-1405)

ext/tensorflow.mk, jml-build/functions.mk, jml-build/print-timing.awk, jml-build/python.mk, mldb_macros.mk
This further prettifies the output of the MLDB build, and keeps full timing statistics for all tests.  This allows us to easily compare two trees for differences in performance.
It also modifies the default display to show CPU seconds, not elapsed seconds, as this is less variable run over run.  Finally, it shows the average number of cores used by the test.
=> Improved stats collection & prettified (MLDB-1397)

core/function.cc, core/function.h, core/plugin.cc, core/plugin.h, mldb_macros.mk, rest/rest_request_router.h, server/function_collection.cc, server/plugin_collection.cc
Adds the ability for functions to have custom routes, and for plugins to host their own static content.
Concrete use-case is to allow the Tensorflow plugin to host a graph that can be used to explore a loaded model, as well as an eventual Tensorboard integration.
=> MLDB-1369 MLDB-1419 routes

sql/sql_expression.cc, sql/sql_expression.h, testing/MLDB-909-simple-WHEN-expression.py, testing/sql_expression_test.cc
This is the new syntax for at() and to_timestamp() functions.  The new syntax is in fact interpreted as a builtin function call.
Comments on the syntax are welcomed.   I will update the test to the new syntax once I get the green light on that.
=> [MLDB-1357] turned to_timestamp and at function into operators

mldb_macros.mk
Stops the tests running over and over when they depend on a plugin.
Verified manually that a change to the plugin still causes the tests to be rerun.
=> Don't depend on phony target for plugin tests (MLDB-1456)

core/function.h, core/mldb_entity.h, core/procedure.h, plugins/classifier.cc, rest/http_rest_endpoint.h, utils/log.cc, utils/log.h, utils/log_fwd.h
This is an early stage of the logger integration to see what you think:
- all entities will have a link to its class logger and logger output is specific for each class (here ClassifierProcedure) and use the type name for lookup
- cerr are changed to info level in most cases
The output looks like this:
```
Datacratic::MLDB::ClassifierProcedure [2016-03-07T13:16:19.901--5:00] info initialized feature space in elapsed: [0.00s cpu, 0.9277 mticks, 0.00s wall]
Datacratic::MLDB::ClassifierProcedure [2016-03-07T13:16:19.901--5:00] info extracted feature vectors in elapsed: [0.00s cpu, 1.3139 mticks, 0.00s wall]
Datacratic::MLDB::ClassifierProcedure [2016-03-07T13:16:19.902--5:00] info merged feature vectors in elapsed: [0.00s cpu, 0.3506 mticks, 0.00s wall]
Datacratic::MLDB::ClassifierProcedure …
```
=> Mldb 1342 added call to logger to ClassifierProcedure

core/dataset.cc, core/dataset.h, plugins/tabular_dataset.cc, plugins/tabular_dataset.h, server/bound_queries.cc, server/dataset_context.cc, server/dataset_context.h, server/forwarded_dataset.cc, server/forwarded_dataset.h, sql/sql_utils.cc, sql/sql_utils.h, testing/MLDB-1305_rowNames_join.py
The WHERE optimizations are done by the dataset but the dataset doesn't know its alias which is context-dependant so we had to pass the alias to the dataset.
=> MLDB-1454 remove table name in WHERE for function

plugins/accuracy.cc
recordRows is NOT guaranteed to be multithread-safe and so calls to it must be properly protected.
=> Quick fix for Accuracy procedure thread-safety issue

plugins/embedding.cc, plugins/git.cc
- Commit is properly called, to avoid empty dataset issues
- We accept messages with ISO-8859-1 encodings, and other encodings that are unknown simply cause the commit message to be skipped.
- Note that the test is not enabled, since there is a separate error caused by problems with expression scope nesting.
=> Fixed git import issues (MLDB-1487)

Building.md, container_files/public_html/doc/builtin/functions/ClassifierApply.md, container_files/public_html/doc/rest.html, ml/jml/boosted_stumps.cc, ml/jml/boosted_stumps.h, ml/jml/classifier.cc, ml/jml/classifier.h, ml/jml/committee.cc, ml/jml/committee.h, ml/jml/decision_tree.cc, ml/jml/decision_tree.h, ml/jml/decoded_classifier.cc, ml/jml/decoded_classifier.h, ml/jml/feature_set.h, ml/jml/glz_classifier.cc, ml/jml/glz_classifier.h, ml/separation_stats.cc, ml/separation_stats.h, plugins/accuracy.cc, plugins/classifier.cc, testing/MLDB-174-regression.py, testing/MLDB-256_accuracy_accepts_all_cls_modes.py, utils/command.h
This fixes a couple of things. Apologies for mixing up things. A commit-by-commit review is probably easier.
- Changed Classifier_Impl inferface so that the label passed in explain function is now a float so we can deal with regression tasks.
- Added check for a null feature-set when we try to use the classifier function with no columns matching (ie doing a select on columns where none exist in the dataset)
- Binary stats track weighted counts as well as unweighted counts to fix the accuracy plugin when doing a weighted training. the code incremented counters assuming it got actual example counts, but when doing a weighted training, examples were represented by floats possibly smaller than 1 so counters would not move in the expected manner
=> Mldb 1443 cls test coverage

core/dataset.h, plugins/importtext_procedure.cc, plugins/json_importer.cc, plugins/sparse_matrix_dataset.cc, plugins/sparse_matrix_dataset.h, sql/coord.cc, testing/MLDB-1360-sparse-mutable-multithreaded-insert.cc, testing/testing.mk
This adds a test-case and fixes the multithreading issues for the sparse mutable dataset.
It also removes mutexes in the import procedures, and fixes a few other small-ish bottlenecks.  As part of doing that, the indentation of the import text producedure was fixed.
Effect is that bid request importation goes from 2,000 bid requests per second to 20,000.
=> MLDB-1360 sparse mutable multithreaded insert

sql/cell_value.cc, sql/cell_value.h, sql/coord.cc, sql/coord.h, sql/expression_value.cc, testing/cell_value_test.cc, types/itoa.h, types/json_printing.cc, types/json_printing.h
This removes many of the bottlenecks and inefficiencies in JSON importing.  It moves the speed up from parsing around 16,000 complex records per second to around 23,000.
=> MLDB-1508 json import improvements

core/dataset.cc, core/dataset.h, testing/MLDB-180-basic-join.js
…tcolumn.
getcolumn, getcolumnvalues and the like all assume an existing column and will throw if it doesnt exist, so if the column is user-provided, we need to check that its a valid column so that we can return 0 rows instead of a 404/500 http.
=> Mldb 1384 where in outer join

core/dataset.h
Trivial addition of a virtual destructor, to allow subclasses to actually free their resources.
=> Made RowStream destructor virtual (MLDB-1520) (TRIVIAL)

core/dataset.cc, core/dataset.h, plugins/tabular_dataset.cc, server/bound_queries.cc, testing/MLDB-1428-text-sparse-output.py
-Fix a off-by one error in tabular dataset
-Made clear that generateRowsWhere must return an exact set
-`where` expression no longer evaluated outside of generateRowsWhere when generateRowsWhere is called. Should have a positive performance impact on large, non-group-by queries.
-Dont allow generateRowsWhere to cast other values to string when comparing to rowName(). This is because we evaluated rowName() to a string type when we evaluated SQL, so if we allow generateRowsWhere to cast ints to rownames in an optimized path, it would give a different result than the non-optimized path.
-Currently all row names are stored as strings in Coord and all rowName() evaluated to a string.
=> MLDB-1513 fix issues with tabular dataset and row generation in queries

container_files/public_html/doc/builtin/sql/ValueExpression.md, server/bound_queries.cc, sql/builtin_aggregators.cc, sql/builtin_functions.cc, testing/MLDB-1554-string-agg.js, testing/testing.mk
This PR adds the string_agg(), vertical_string_agg() and horizontal_string_agg() functions to MLDB.  They are equivalent to the Postgresql versions.
There is also a fix for an unrelated issue that was identified in testing, where the argument indexes weren't in sync with the aggregator indexes when analyzing the queries in a group by.
=> MLDB-1554 concat aggregator

jml-build/get_git_revision.sh
The original code would break in mysterious ways when the only change to
a submodule was new files and when using DOCKER_ALLOW_DIRTY=1.
Terminal would stay red and build would continue even if revision could
not be obtained.
=> Check for 'modified' and 'new file' in submodules

sql/sql_expression.cc, sql/sql_expression_operations.cc, sql/sql_expression_operations.h, testing/MLDB-1567-empty-literal.js, testing/testing.mk
This also improves the error message for when table expressions are mis-parsed to be more helpful to the user.
=> Fixed empty literal parsing; improved error message for table expressions (MLDB-1567)

core/dataset.cc, sql/binding_contexts.h, sql/sql_expression_operations.cc, sql/sql_expression_operations.h, testing/MLDB-1563-keys-values-of.js, testing/testing.mk
This fixes the issue whereby we couldn't find functions inside the rowName() IN (KEYS OF ...) expression when it hit the optimized path for rowName().
=> Fixed use of context in optimization of IN (KEYS OF ...) (MLDB-1563)

builtin/joined_dataset.cc, core/dataset.cc, core/dataset.h, plugins/svd.cc, plugins/tabular_dataset.cc, server/analytics.cc, server/bound_queries.cc, server/dataset_collection.cc, server/parallel_merge_sort.h
Added a new algo to perform a quicksort in multithread.
On fmaillet's test case of a left join on 41M+ rows (on one side, less on the other), with this PR we save:
About 60 seconds by sorting in parallel in join_dataset
About 173 seconds (3 minutes!) by sorting in parallel in QueryBasic
About 20 seconds by not sorting in TabularDataset::getrownames
In total we cut the time necessary to perform this large outer join by more than half. There may be a larger refactoring to make it much faster but those were the low-hanging apples.
=> Join sort optims

base/testing/thread_pool_test.cc, base/thread_pool.cc, base/thread_pool.h
Two improvements to the thread pool:
1.  We are more aggressive at backing off busy stealing of work when there is no more work to do, to reduce idle CPU usage (plus test): MLDB-1538
2.  We document, and enforce, a no job exception policy for jobs submitted to the thread pool: MLDB-1532.  Note that the abstractions built on the thread pool, like parallelMap, still return exceptions; it's just that the jobs they launch catch and track them internally.
=> MLDB-1538 threadpool

base/testing/thread_pool_test.cc, base/thread_pool.cc
If we created a thread, submitted jobs, and then the thread exited before we had a chance to run the jobs, those jobs would be lost.  Instead, when a thread exits we wait for its queue to empty before doing so.
This fixes the issue with some tests in pro hanging on exit.
The test failed before the fix was made.
=> Test and fix for thread jobs disappearing with thread exit (MLDB-1579)

arch/exception.cc, http/http_exception.cc, rest/rest_request_router.cc, sql/builtin_functions.cc, testing/MLDB-1355-explain-bad-alloc.js, testing/testing.mk
More friendly error messages when out of memory:
```javascript
--------------------------[Exception thrown]---------------------------
time:   2016-04-28T21:11:04Z
type:   std::bad_alloc
pid:    66164; tid: 66165
what:   std::bad_alloc
2016-04-28 17:11:04.096 javascript {
"details" : {
"context" : {
"error" : "Out of memory.  A memory allocation failed when performing the operation.  Consider retrying with a smaller amount of data or running on a machine with more memory.  (std::bad_alloc)"
},
"functionArgs" : [],
"functionName" : "_fail_memory_allocation"
},
"error" : "Executing builtin function _fail_memory_allocation: Out of memory (std::bad_alloc)",
"httpCode" : 400
}
```
=> Explain std::bad_alloc message (MLDB-1355)

sql/sql_expression.cc, testing/sql_expression_test.cc
Fixes issues with COLUMN EXPR(...) that users have encountered.
=> Allow space between COLUMN EXPR and ( to be optional (MLDB-1590)

plugins/tabular_dataset.cc, testing/MLDB-1597-regression.py
Fixes the issue identified in MLDB-1619, which was caused by the tabular dataset assuming that offset=0 and limit=-1 for all queries.
=> Fixed tabular dataset getRowXXX limit/offset (MLDB-1619)

container_files/public_html/doc/builtin/sql/ValueExpression.md, sql/builtin_functions.cc, sql/sql_expression.cc, sql/sql_expression_operations.cc, testing/MLDB-1631-join-transpose-where-rowname.js, testing/testing.mk
Fixes two things:
- Segfault caused by binary operations not filling in the expression that they came from
- Refactor of regex builtins to allow a non-constant regex string
=> MLDB-1631 join transpose where rowname

builtin/joined_dataset.cc, builtin/joined_dataset.h, core/dataset.cc, core/dataset.h, sql/execution_pipeline.cc, sql/execution_pipeline.h, sql/execution_pipeline_impl.cc, sql/execution_pipeline_impl.h, sql/sql_expression.h, sql/table_expression_operations.cc, testing/MLDB-1616-row-dataset-segfault.js, testing/testing.mk
This allows for joins on things that aren't backed by a dataset, for example row_table(), also fixing a segfault when it was attempted.
The implementation will detect when there is no materialized dataset behind one or both sides of a join, and fall back to the new executor instead.
It also lays the groundwork for correlated subselects.
=> Allow joining on table expressions (eg, row_table) (MLDB-1616)

sql/path.cc, sql/path.h, sql/testing/path_test.cc
Self explanatory... this allows for paths to contain empty elements, just like JSON (which allows empty keys).
=> Allow empty path elements (MLDB-1635)

builtin/joined_dataset.cc, sql/join_utils.cc, sql/join_utils.h, testing/MLDB-1624-more-join-test.py
This is fixing one case where a join with cross conditions other than equality was not accepted.
=> Mldb 1664 join with non-equijoin condition (e.g. inequality)

ml/jml/decision_tree_generator.cc, ml/jml/feature.h, plugins/classifier.cc, testing/MLDB-1597-regression.py
Fixes two things:
1.  Classifier training silently ignored (with just a log message) when it couldn't save the file; this now will lead to failure
2.  Decision tree would not properly detect when there was no weight in a leaf, and continuously re-split.  This would lead to us trying to serialize a MISSING feature when serializing.
=> Fixed DT regression, classifier file saving (MLDB-1660)

server/dataset_context.cc, testing/MLDB-1235-temporal-aggregators.py, testing/MLDB-180-basic-join.js
Fixes problems with the wildcard matching and prefix replacement from MLDB-1486.
=> MLDB-1629 fix nesting in column names within join

builtin/merged_dataset.cc
This will solve the issue of the WHERE not getting applied on the merged dataset in some cases.
=> MLDBFB-545 missing filter in merge dataset getColumnValues

mldb_macros.mk, plugins/embedding.cc, plugins/importtext_procedure.cc, plugins/tabular_dataset.cc, server/dataset_collection.cc, sql/cell_value.cc, sql/execution_pipeline.cc, sql/expression_value.cc, sql/path.cc, sql/path.h, sql/testing/path_test.cc, testing/MLDB-180-basic-join.js, testing/MLDB-878_experiment_proc.py, valgrind.supp
This patch moves from a vector representation to an indexed string representation for paths.  It results in roughly a 2x speed improvement for query performance, due to less pointer chasing, and mostly closes the performance gap with the pre-singularity version of MLDB.
There are other improvements possible; this is the low-hanging fruit.
=> MLDB-1632 path optimizations

jml-build/functions.mk
When not escaped, \ and $ would cause a mismatch between the key stored
in the .make_hash_cache file and the key returned to make, thereby
causing costly execution of `bash -c 'echo ... | md5sum'` and adding a
duplicate target to .make_hash_cache
This fixes the cache miss cases and speeds up the build startup time.
=> Escape \ and $ in command_key. Fixes cache miss.

soa/service/s3.cc
https://github.com/mldbai/mldb/pull/437/files#diff-1df7fd725c20425abb80dbf865d2a6f2R2190
Si tryPop retourne instantanément, ça infinite looooooop.
=> Fix s3 tryPop infinite loop

container_files/init/uwsgi_validator_runner.sh
Option name is misleading, it disables access logging, not all logging.
Exceptions and operational messages such as child proc restarting are
still logged.
=> Disable access logging for uwsgi_validator_runner

core/procedure.h, plugins/bucketize_procedure.cc, plugins/classifier.cc, plugins/tfidf.cc
Avoids including spdlog as part of the plugin API headers and thus exposing our users to it.
=> Removed spdlog from public API (MLDB-1757)

plugins/tabular_dataset.cc, plugins/tabular_dataset_chunk.h
Also fixes issues with row name generation when offset and limit aren't at their default values.
This reduces by about 80% the time elapsed creating the row index of a large tabular dataset post-import.
=> Sharded row index for Tabular dataset (MLDB-1762)

plugins/tabular_dataset.cc, plugins/tabular_dataset_chunk.h, sql/path.cc, sql/path.h, sql/testing/path_test.cc
Goes from roughly 80 byte overhead per row to a 16 byte overhead when row names are just integers.
=> Reduced storage requirements where row names are integers (MLDB-1763)

server/dataset_context.cc
Pure performance improvement.  We use a generic emulated version of rowPath() rather than the one provided by the dataset by overriding in the wrong place.
=> Use reasonable form of implementation of rowPath() function that doesn't parse rowName() (MLDB-1765)

sql/expression_value.cc, sql/path.cc, sql/path.h
Pure performance improvement: don't copy and sort something that's already sorted.
=> Don'e re-sort and copy already sorted Structured ExpressionValues (MLDB-1764)

sql/sql_expression.cc, sql/sql_expression_operations.cc
Optimization to reduce copying that becomes a bottleneck when creating small embeddings like 3-space coordinates.
=> Copying optimizations for query execution (MLDB-1770)

Building.md, sql/sql_expression.cc, sql/sql_expression.h
Saves some slightly more expensive checks when converting row scopes.
=> Don't perform extra SqlRowScope type checking (MLDB-1421)

sql/sql_expression.cc, sql/sql_expression_operations.cc, testing/MLDB-1779-select-column-expr-pathnames.js, testing/testing.mk
It was assuming strings and using columnName() not columnPath() as the default AS
=> Fixed pathnames for COLUMN EXPR (MLDB-1779)

plugins/importtext_procedure.cc, testing/MLDB-1603-nonprintable-chars-json.js, testing/testing.mk, types/json_printing.cc, types/json_printing.h
Allows all ASCII control characters to be represented in JSON, as per the JSON spec.
=> MLDB-1603 non printable chars json

testing/MLDBFB-509_pushed_non_printable_char_cant_query.py
These tests no longer need to be expected failures, as they now pass.
=> Made fixed tests expected pass (MLDB-1630)

Building.md, ext/tensorflow.mk, jml-build/functions.mk, tensorflow/tensorflow_plugin.cc
Fixes a few bits and pieces that allow CUDA support to be built for Tensorflow.
It's a no-op in the official build as it requires the WITH_CUDA variable to be set, which isn't by default.
Note that CUDNN isn't currently supported.
=> CUDA build now working (MLDB-1786)

vfs_handlers/exception_ptr.cc, vfs_handlers/exception_ptr.h, vfs_handlers/s3_handlers.cc, vfs_handlers/vfs_handlers.mk
This PR modifies the S3 downloader and uploader classes by making use of the asynchronous methods offered by S3Api, rather than using multiple threads along with the blocking methods.
This finalizes MLDBFB-239 and brings the actual benefits expected from it, which is to reduce the number of context switches and thereby enhancing the scalability of the s3 subsystem.
=> Mldbfb 239 http client s3 handlers

testing/MLDB-1810-new-executor-rowpath.js, testing/testing.mk
Adds a testcase that was left behind in previous changes that fixed the underlying problem.
=> Added test for already fixed rowPath() with new executor (MLDB-1810)

builtin/joined_dataset.cc, server/dataset_context.cc, server/dataset_context.h
Refactoring towards allowing ExpressionValue to be passed into a Dataset Scope to remove the dependency on MatrixNamedRow et al.
=> Refactored dataset scope (MLDB-1811)

plugins/tabular_dataset_chunk.h, sql/cell_value.cc, sql/cell_value.h
Since we have code to compress doubles but not timestamps, this allows us to take advantage of that code to do a better job at storing the timestamp column too.
=> Store timestamps as numbers to improve compression options in Tabular (MLDB-1815)

core/dataset.cc, core/dataset.h, server/analytics.cc, server/analytics.h, server/bound_queries.cc, server/bound_queries.h, sql/execution_pipeline.cc, sql/execution_pipeline.h
Provides an interface that can be used to receive results from an analytics query one at a time.  Also fixes constness issues in the interface, and returns the customary bool for a short-circuited exit.
NOTE: the queryStructuredIncremental function is not tested yet.  There is a coming commit that uses it to implement tested code.
=> Allow for incremental queries (MLDB-1816)

container_files/public_html/doc/builtin/sql/ValueExpression.md, http/http_exception.cc, http/http_exception.h, plugins/json_importer.cc, server/bound_queries.cc, sql/builtin_aggregators.cc, sql/builtin_functions.cc, sql/builtin_http_functions.cc, sql/expression_value.cc, sql/expression_value.h, sql/sql_expression.cc, sql/tokenize.cc, sql/tokenize.h, testing/MLDB-907-tokenize.py, testing/MLDBFB-573_parse_json.py, types/enum_description.h, types/json_parsing.cc, types/pair_description.h, types/structure_description.h, types/testing/value_description_test.cc, types/utility_descriptions.h, types/value_description.cc
Removes the getStructured() method from ExpressionValue, which should basically never be used and couples the semantics of the ExpressionValue class to its internal implementation.
The main uses of the method were in parsing options to functions, which were refactored to use the ValueDescription system (which also allows for generated documentation).  As part of those changes, a new `addAuto()` function was added to `StructureValueDescription` to allow default values to be automatically inferred, and some validation errors were fixed in the JSON parsing code.
The optimized path for aggregators on a static set of columns was also fixed to no longer use getStructured; this should avoid several situations where using embeddings with aggregators would have caused issues.
Finally, a couple of …
=> Refactored uses of ExpressionValue::getStructured() and removed (MLDB-1818)

core/dataset.cc, plugins/embedding.cc, plugins/pooling_function.cc, plugins/tabular_dataset.cc, plugins/tabular_dataset.h, server/analytics.cc, server/analytics.h, server/bound_queries.cc, server/bound_queries.h, sql/builtin_aggregators.cc, sql/expression_value.cc, sql/sql_expression.cc, sql/sql_expression.h
This simplifies and streamlines the query logic by removing the use of MatrixNamedRow (an exploded format) in query processing and sticking to ExpressionValues.
It has an effect on efficiency: in cases where there is SQL processing, it will be faster (as no converting back and forth from ExpressionValues is needed).  However, for a select * it will be somewhat slower.
There is a forthcoming patch to fix that situation by making the ExpressionValue be used through the entire query processing path.
Note that it includes the MLDB-1818 diff, as it's built on top of that code.  Once that branch is merged, this can be rebased and will end up substantially smaller.
=> MLDB-1813 matrix named row removal

sql/binding_contexts.cc, sql/binding_contexts.h, sql/sql_expression_operations.cc, testing/MLDBFB-646-column-expression-select.js, testing/testing.mk
Allows the `SELECT` part of `COLUMN EXPR (...)` to be used.
@simlmx FYI
@jpilaul would be worth adding to the tutorial on COLUMN EXPR
```
select column expr(select {a: value() * 10, b: value() * 20} ) named 'res' from (select x:1, y:2)
```
```
[
[ "x.a", 10, "-Inf" ],
[ "x.b", 20, "-Inf" ],
[ "y.a", 20, "-Inf" ],
[ "y.b", 40, "-Inf" ]
]
```
=> Fixed SELECT in column expression (MLDBFB-646)

plugins/tabular_dataset.cc
Fixes an issue with the initAt() function over Tabular datasets whereby it could end up at an invalid iterator position if it started off between chunks.
One character fix.
=> Fixed tabular dataset (MLDB-1837)

plugins/sparse_matrix_dataset.cc, plugins/sparse_matrix_dataset.h, testing/MLDB-1098-csv-export.py, testing/MLDB-1428-text-sparse-output.py, testing/MLDB-415-rawquery.js
Takes import of a 1.6 million line CSV file into sparse.mutable from 4 minutes to 36 seconds, and greatly reduces memory usage too.
=> Sped up sparse mutable chunked recording (MLDB-1838)

sql/execution_pipeline_impl.cc, testing/MLDB-1843-select-disappearing-values.js, testing/testing.mk
Fixes problems with dynamic schemas in the new executor's table expressions.
=> Handle dynamic columns in new executor (MLDB-1843)

sql/path.cc, sql/path.h
Simple fix to avoid using a std::string as a temporary.
=> Reduced Path allocations constructing from PathElement (MLDB-1845)

plugins/importtext_procedure.cc, plugins/matrix.cc, sql/binding_contexts.cc, sql/execution_pipeline_impl.cc, sql/expression_value.cc, sql/expression_value.h, sql/sql_expression_operations.cc, testing/MLDB-1843-select-disappearing-values.js, testing/MLDB-654-classifier-function-info.js, testing/MLDB-800-nested_sql_query.py
Fixes a typo causing problems with structured selects in the new executor, and a type system bug that was marking an object with fixed fields but variable subfields as having no schema variability.
=> More fixes for types and new executor (MLDB-1843)

builtin/transposed_dataset.cc, builtin/transposed_dataset.h, plugins/sparse_matrix_dataset.cc, server/dataset_context.cc, sql/expression_value.cc, sql/expression_value.h, sql/path.cc, types/json_printing.cc
A set of micro-optimizations that take the columnCount() portion of the Reddit benchmark from around 4 seconds to around 1.5 seconds, removing most of the performance loss associated with moving to ExpressionValues.
Primarily this involves reducing the amount of sorting, now that the ExpressionValue itself is always sorted internally, as well as optimizations for less copying in the Transposed dataset, increasing the set of conditions under which memcmp() can be used in path comparisons, and avoiding temporary values when parsing paths in the sparse matrix dataset.
=> MLDB-1868 path performance regressions

plugins/dist_table_procedure.cc, testing/MLDB-1750-dist-tables.py
We keep track of the stats when the value is NULL, we we might as well return it!
Comes with a test case.
=> dist table function returns stat for empty cell too

container_files/public_html/doc/builtin/sql/SelectExpression.md, container_files/public_html/doc/builtin/sql/ValueExpression.md, sql/binding_contexts.cc, sql/builtin_functions.cc, sql/builtin_functions.h, sql/sql_expression_operations.cc, testing/MLDBFB-646-column-expression-select.js
Sorts out some of the confusion around using `COLUMN EXPR (AS parse_path(columnName())` by adding `flatten_path` and `unflatten_path` functions that do what would be expected of them and can be used as a matched pair.
Also adds more efficient implementations of the `columnPathElement()` and `columnPathLength()` functions, and fixes an issue where the `AS` expression was applied twice in some dynamic `COLUMN EXPR` contexts.
=> Better flattening/unflattening of paths (MLDBFB-666)

sql/expression_value.cc, tensorflow/MLDB-1736-tensorflow-builtins.js, tensorflow/tensorflow_plugin.cc, testing/MLDB-1486-embedding-types.js
Fixes various embedding type inference and maintenance problems to allow TF functions that don't accept doubles to work properly.
=> Allow inference and use of type attributes for TF builtins (MLDB-1877)

sql/binding_contexts.cc, sql/binding_contexts.h, sql/builtin_functions.cc, sql/builtin_functions.h, sql/eval_sql.cc, sql/eval_sql.h, sql/expression_value.cc, sql/expression_value.cc.orig, sql/expression_value.h, sql/path.cc.rej, sql/sql.mk, sql/testing/eval_sql_test.cc, sql/testing/sql_testing.mk
This is an internal function that is used by the lidar plugin.  It allows for functionality to be implemented in SQL and C++ parameters to be bound in seamlessly, enabling things like
```c++
SqlBindingScope scope;
uint8_t alpha = 0;  // set the transparency of the pixel
ExpressionValue singlePixelPng = evalSql(scope, "tf_EncodePng([[[0,0,0,$1]]])", alpha);
```
=> Added eval_sql function (MLDB-1876)

core/value_function.cc
Replaces exception fallback with one that goes through JSON to allow all types to be converted.  This means that the ValueFunction interface is now able to support most types, rather than just ExpressionValues and CellValues.
=> Allow all JSON-compatible types to pass to ValueFunction (MLDB-1880)

types/array_description.h, types/list_description_base.h, types/testing/value_description_test.cc
Trivial change to allow std::array to be used in ValueDescriptions.
=> Added ValueDescription for std::array (MLDB-1881)

jml-build/get_git_revision.sh
- Allow submodule build path to have one level of leading directory
this allows mldb/ext/submodule to be mapped correctly yo etx/submodule
- Replace / with - in submodule name to avoid `SMFILESUSED` creation problems
=> Tweaks to submodule handling code

testing/MLDB-1597-regression.py
On outer join, not all rows contain all the columns.  This is fixing the test but a bigger issue remains  that some of the rows are duplicated.  This is coming as a separate PR.
=> remove the randomness in the test

sql/join_utils.cc, sql/join_utils.h
Trivial simplification of the code to unnecessary AnnotedJoinCondition::Side members.
=> removed transitory members from AnnotedJoinCondition::Side

container_files/public_html/doc/builtin/sql/ValueExpression.md, sql/builtin_functions.cc, testing/MLDB-1336-builtin-checks.py, testing/MLDB-781-numeric-functions.js
- add support for log(x) and log(b,x) that match postgresql's functions
- make log/ln and sqrt not fail on 0/negative values and return nan/-inf instead
- fix a few typos in the doc
- simplify the numeric-functions test file
=> MLDB-1735 make ln/log behave like postgresql's

tensorflow/MLDB-1736-tensorflow-builtins.js, tensorflow/tensorflow_plugin.cc
Allows the conv2d artifact in Tensorflow to work.
Note that despite the documentation, only the NHWC encoding works, which makes the format of image inputs a little bit funky.  There are other Tensorflow ops that may help to coerce the data into the appropriate format.
Also, despite the documentation the DT_DOUBLE type doesn't work for convolutions.
=> MLDB-1906 ts conv2d

arch/arch.mk, arch/gc_lock.cc, arch/gc_lock.h, arch/gc_lock_impl.h, arch/shared_gc_lock.cc, arch/shared_gc_lock.h, arch/testing/arch_testing.mk, arch/testing/gc_lock_test_common.h, arch/testing/gc_test.cc, arch/testing/shared_gc_lock_test.cc
This fixes a major portability problem (only x86_64 has 128 bit atomics, whereas basically every interesting platform has 64 bit atomics).
The testing code is pretty comprehensive, but this is a very low-level primitive and so we should keep an eye out for test failures in concurrency.
We now only use std::atomic to implement the functionality; no assembler is required any more.
The changes made were as follows:
1.  The visibleEpoch field was removed, and its value inferred from epoch (saving 32 bits)
2.  The exclusive field was removed, and replaced with a single bit on the "in" counter (saving 32 bits).  Note that this reduces that maximum number of threads that can be simultaneously in a critical section from 65535 to 32767.  It shouldn't be a problem in practice, but it is a limit.
3. …
=> No longer require 128 bit atomics for gc_lock (MLDB-1909)

.gitmodules, Building.md, base/thread_pool.cc, base/thread_pool.h, mldb_base/docker_create_mldb_base.sh, plugins/lang/js/dataset_js.cc, plugins/lang/js/dataset_js.h, plugins/lang/js/function_js.cc, plugins/lang/js/function_js.h, plugins/lang/js/js_common.cc, plugins/lang/js/js_common.h, plugins/lang/js/js_function.cc, plugins/lang/js/js_loader.cc, plugins/lang/js/js_utils.cc, plugins/lang/js/js_utils.h, plugins/lang/js/js_value.cc, plugins/lang/js/js_value.h, plugins/lang/js/mldb_js.cc, plugins/lang/js/mldb_js.h, plugins/lang/js/mldb_js_plugin.mk, plugins/lang/js/procedure_js.cc, plugins/lang/js/procedure_js.h, testing/MLDB-980-unquoted-string-crash.js
Upgrades v8 to the very latest version, removing a system dependency and allowing arm64 builds (the version of v8 we used didn't work on arm64).
This involves the following changes:
1.  Discovered how to build v8 using <strike>scons</strike> <strike>GYP</strike> GN, using the system ICU (which clashes with the one included in v8), and with cross-compilation available.  The results of this work are in the mldbai/v8-cross-build repo, and the output is cached in the v8-cross-build-output repo which is included in MLDB under ext/.
2.  Updated all of the JS code to the latest v8 API.  This was mostly mechanical, and in general the new API is cleaner and better which improved the quality of the JS binding code.
3.   Created a new `Platform` implementation for v8 with access to the thread pool …
=> MLDB-1913 v8 upgrade

container_files/public_html/doc/builtin/sql/ValueExpression.md, sql/builtin_aggregators.cc, sql/builtin_functions.cc, sql/builtin_functions.h, testing/MLDB-1554-string-agg.js
The `string_agg` operator will aggregate in whatever order it gets fed values.  While this is sometimes OK, that order happens to depend upon the order that std::unordered_map holds entries, and so varies from compiler to compiler.  This makes unit testing hard and is basically wrong.
This patch changes that to by default sort them alphabetically first.  If that isn't what was wanted, it now accepts a third argument that is the sort key, and the values will be sorted by that first before sorting alphabetically to break ties.  This allows us to pass for example the rowPath() as a sort key and get a consistent ordering across the underlying dataset.
Documentation and tests were updated.
=> Added optional ordering to string_agg (MLDB-1924)

.gitmodules, ext/protobuf.mk, ext/tensorflow.mk
We should never need to download gmock again...
=> Use internal gmock for protobuf (MLDB-1926)

ext/tensorflow.mk
This will make most of the tensorflow build wait on the protobuf build.
It fixes problems like this:
```
mldb/ext/tensorflow/tensorflow/core/framework/op_def.pb.h:9:42: \
fatal error: google/protobuf/stubs/common.h: No such file or directory
```
=> Add protobuf dep to generate_tensorflow_op targets

ext/jpeg.mk
Should fix :
```
In file included from ./mldb/ext/jpeg/jaricom.c:17:0:
./mldb/ext/jpeg/jinclude.h:20:55: fatal error: jconfig.h: No such file or directory
```
The original code didn't seem to add a dependency, but it might be magic beyond my gmake powers.
Replaced with an obvious construct.
@jeremybarnes  can you double check please?
=> Wait for jconfig.h before building the lib

container_files/public_html/doc/builtin/procedures/Accuracy.md, ml/separation_stats.cc, plugins/accuracy.cc, testing/MLDB-256_accuracy_accepts_all_cls_modes.py, testing/test_classifier_test_proc.py
Simply rename the confusing "f" to "f1Score" (and "bestF" to "bestF1Score") in the classifier.test output.
=> [MLDB-1928] rename f to f1Score

ext/protobuf.mk, ext/tensorflow.mk
- Add dependency on protobuf headers for pb.h and pb.cc files
- install protobuf in proper directory when $BIN $LIB and INC are changed
(docker builds)
=> protobuf dependency fixes

ext/tensorflow.mk, ext/tf_load_kernels.cc, jml-build/sample.local.mk
Our build for Tensorflow had a hard-coded option to use avx operations, which are not supported on older 64 bit CPUs.  By the same token, it was unable to make use of avx2 and FMA instructions available on new 64 bit CPUs.
This patch modifies the building of the Tensorflow kernels to build a separate library optimized for each processor architecture, and then select the appropriate one at runtime.
Note that it adds quite a long time to the build process, since there are four different options built.  Adding `TF_KERNEL_VARIANTS:=avx` or `TF_KERNEL_VARIANTS:=sse42` or `TF_KERNEL_VARIANTS:=avx2` to local.mk will cause only a single one to be built, improving compile times.
=> Dynamic load Tensorflow kernels for CPU (MLDB-1939)

ext/protobuf.mk
Fixes build failures when TMP is an absolute path, but keeps it working when TMP is a relative path.
=> Fixed protobuf sched_yield failure in configure (MLDB-1953)

ml/jml/boosted_stumps_generator.h, ml/jml/boosting_generator.h, ml/jml/decision_tree_generator.h, ml/jml/early_stopping_generator.h, ml/jml/glz_classifier_generator.h, ml/jml/null_classifier_generator.h, ml/neural/perceptron_generator.h
Almost fixes clang build. There is a problem with tf.
```
./mldb/ext/tensorflow/tensorflow/cc/framework/scope.cc:25:8: error: constructor for 'tensorflow::Scope' must explicitly initialize the const member 'colocation_constraints_'
Scope::Scope(Graph* graph, Status* status, Scope::NameMap* name_map)
^
mldb/ext/tensorflow/tensorflow/cc/framework/scope.h:245:36: note: 'colocation_constraints_' declared here
const std::unordered_set<string> colocation_constraints_;
```
Any ideas?
=> clang fixes

ml/algebra/least_squares.h, sql/expression_value_conversions.cc
Remaining error with... TF.
```
./mldb/ext/tensorflow/tensorflow/cc/framework/scope.cc:25:8: error: constructor for 'tensorflow::Scope' must explicitly initialize the const member 'colocation_constraints_'
Scope::Scope(Graph* graph, Status* status, Scope::NameMap* name_map)
^
mldb/ext/tensorflow/tensorflow/cc/framework/scope.h:245:36: note: 'colocation_constraints_' declared here
const std::unordered_set<string> colocation_constraints_;
```
=> Fix some clang build errors

base/base.mk, mldb_base/docker_create_mldb_base.sh
... it's not needed anymore (we use the standard library)
=> Removed boost_thread as dependency (MLDB-2029)

.gitmodules, testing/run_json_test_suite.cc, testing/testing.mk, types/json_parsing.cc, types/json_parsing.h
This adds a large JSON test suite, and fixes the handling of UTF-16 surrogate pairs (which are the way that characters out of the basic multilingual plane are handled).  It also makes handling of extremely large numbers more robust (if they are too big for a long, they become a double, and if they are too big for a double, they become infinity rather than crashing as before).
The test failure is spurious.
=> Added JSONTestSuite tests (MLDB-2032)

types/types.mk
Should fix this error:
```
/bin/cp: cannot create regular file ‘build/x86_64/tmp/docker-mldb/opt/lib/date_timezone_spec.csv’: No such file or directory
```
=> Explicit dependency on parent dir creation

Building.md, arch/testing/bit_range_ops_test.cc, jml-build/arch/get-port-package-deps.sh, jml-build/arch/install-port-package.sh
- Use `-o APT::Architecture=$ARCH` in apt cmds instead of relying on `dpkg --add-architecture`
- Doc update
- Tweak test to avoid `-Werror=overflow` in a test which does an overflow on purpose.
=> Cross compilation fixes

sql/execution_pipeline_impl.cc, sql/execution_pipeline_impl.h, testing/MLDB-2040_join_tests.py, testing/testing.mk
Refactor both the equi and cross join pipeline executor to better handle left, right and full outer joins.
We cannot output a row as an outer row until its been tested against every single other row it could match with.
For left or right cross joins, we choose the proper side to loop on first to be efficient (for example if its a right join, we loop on right first). This way we avoid having to cache all rows. For a full cross join, we dont have a choice but to cache all rows on one side and remember if they've ever been output.
For equi joins, we already had a sliding window row cache for the left side, so we now also keep track of whether each row was ever matched, and selectively output an outer row then it gets removed from the cache. This will also help with memory in many cases, as …
=> Mldb 2040 pipeline join refactor

sql/execution_pipeline_impl.cc, testing/MLDB-2074-empty-join.py, testing/testing.mk
Create tests and fix issues for full outer joins in the pipeline executor when one of the dataset is empty.
=> Mldb 2074 empty outer join

ext/tensorflow.mk, tensorflow/tensorflow.mk
Before this patch, the Tensorflow plugin needed to be rebuilt for each GPU architecture.  Now it should work out of the box on basically any deployed server architecture (see list below).
This enables multiple architectures to be built for CUDA, and makes a default list that covers the vast majority of deployed server CUDA architectures:
```
Compute/shader model   Cards
6.1			  P4, P40, Titan X
6.0                    P100
5.2                    M40
3.7                    K80
3.5                    K40, K20
3.0                    K10, Grid K520 (AWS G2)
```
It's a Makefile-only fix, and has basically no effect unless `WITH_CUDA=1` is passed.  Passes all tests on a build with that flag set.
=> Build for multiple CUDA architectures (MLDB-2085)

container_files/init/mldb_runner.sh, container_files/template_vars.mk, mldb_macros.mk, release.mk, server/mldb_runner.cc, templated_files.mk
- passing the mldb.conf when doing make <test> to allow logging
- storing the mldb.conf in the docker image and passing it to mldb_runner
- fix a crash when failing to parse the command line
=> [MLDB-2086] passing the config to mldb_runner in debug and release

ext/tensorflow.mk, ext/tf_cuda_handlers.cc
Modifies the default behaviour from assert() to throw so that a CUDA launch failure is recoverable.  This requires a change to the Eigen library too (behind the submodule).
=> Allow customization of Eigen kernel launch failure behavior (MLDB-2115)

.gitmodules, Building.md, ext/ext.mk, ext/libgit2.mk, mldb_base/docker_create_mldb_base.sh, plugins/git.cc, server/plugin_resource.cc
Adds submodule, build Makefile, and cleans up all of the version dependent code.
This means that mldb_runner's core can now be deployed on several more versions of Debian, as the libgit2 API is not frozen.
It also fixes an occasional segfault in the test cases caused by a bug in the 14.10 system version of libgit2.
=> Made libgit2 an internal dependency fixing several portability errors and crashes (MLDB-2024)

http/http_rest_proxy.cc
This allows for ~3 SYN retransmits on a default linux config.
The idea is to avoid being stuck in connect(2) for too long while still
having a chance of success when going through flaky networks.
The timeout value is not configurable, but I think it is a "saner default" than 5 minutes.
(and you should probably fix your network if you need a higher value).
For the record, nginx's proxy_pass module uses a 60s connect timeout.
=> Lower curl connect(2) timeout from 300s to 20s

ext/svdlibc/doc/svdlibc/index.html, ext/svdlibc/doc/svdlibc/license.html, ext/svdlibc/las2.cc, ext/svdlibc/svdlib.cc, ext/svdlibc/svdlib.h, ext/svdlibc/svdutil.cc, ext/svdlibc/svdutil.h
We had a modified version of 1.34. I backported remote changes from version 1.4 into our copy.
This shows the remote changes cleanly: https://github.com/lucasmaystre/svdlibc/commit/0abfaf8da00ed14f2e275bb4435ca0844f89f936
=> [MLDB-2123] Updated svdlibc to 1.4 by backporting changes

Building.md, Makefile, container_files/nvidia/Dockerfile, container_files/nvidia/README.md, container_files/public_html/doc/builtin/BatchMode.md, container_files/public_html/doc/builtin/Running.md, makefile-main-plugin.mk, mldb_base/docker_create_mldb_base.sh, release.mk, sdk/sdk.mk, testing/MLDB-756-docker-plugin.js
There are a few `quay.io/datacratic/*` left, but I'm unsure of their use:
```
docker_create_dependencies.sh:docker run -i -cidfile tmp/docker_dependencies.cid -v ~/local:/tmp/local -v `pwd`:/tmp/build quay.io/datacratic/platform-deps sh -c 'cat > /tmp/command-to-run && chmod +x /tmp/command-to-run && exec /tmp/command-to-run' <<EOF
docker_create_dependencies.sh:docker commit $CID quay.io/datacratic/dependencies
docker_create_platform_deps.sh:docker run -i -cidfile platform-deps.cid -v ~/local:/tmp/local -v `pwd`:/tmp/build quay.io/datacratic/ubuntu-base sh -c 'cat > /tmp/command-to-run && chmod +x /tmp/command-to-run && exec /tmp/command-to-run' <<EOF
docker_create_platform_deps.sh:docker commit $CID quay.io/datacratic/platform-deps
sdk/Dockerfile:FROM …
```
=> switch quay.io organization to mldb

tensorflow/doc/Tensorflow.md, tensorflow/tensorflow_plugin.cc
Added a new macro so that we can automatically generate the documentation of all the tensorflow operations that are wrapped in MLDB.
=> [MLDB-2131] added a macro to document all TF operations wrapped in MLDB

sql/builtin_functions.cc, sql/expression_value.cc, sql/sql_expression_operations.cc, testing/expression_value_test.cc
Fix wrong implementation of rowLength for embeddings and implement getAtomCount.
rowLength is meant to return the number of columns in the first structured level, and that worked for row representations. However for embeddings representations is was returning the number of atoms. 
If you need the total number of atoms, the proper method is getAtomCount.
=> Fix wrong implementation of rowLength for embeddings

container_files/docker_post_install.sh
Some CI tools impose a lower than usual limit on the maximum UID
that can be used (CircleCI), this should allow mldb to run on such
services.
=> MLDB-2149 Change _mldb's UID from 1234567 to 56789

plugins/for_each_line.cc
Fixed error using gcount() after readline(), leading to thinking that the chunk is bigger than it is and junk characters in between chunks.
=> Fixed offset error on last line of chunk (MLDB-2167)

plugins/importtext_procedure.cc
Reduces memory allocations in the tight loop of text import, improving throughput by around 10%.
The test failure is spurious.
=> MLDB-2191 import text memory allocations

sql/builtin_functions.cc, testing/MLDB-1317-tensor-datatype.js
Fixes incorrect return shape inference for binary operations between an embedding and a scalar.  Includes a test case.
The test failure is spurious.
=> MLDB-2192 value info embedding scalar

plugins/importtext_procedure.cc, sql/expression_value.cc, sql/sql_expression.cc, sql/sql_expression_operations.cc
Several micro-optimizations that between them allow for roughly doubling the speed of the import.text procedure.
Test coverage on these is pretty extensive on existing tests.
=> MLDB-2193 import text optimizations

base/less.h, ml/jml/split.h, ml/separation_stats.h, plugins/behavior/behavior_types.h, plugins/behavior/id.cc, plugins/behavior/mutable_behavior_domain.cc, plugins/behavior_dataset.cc, plugins/binary_behavior_dataset.cc, plugins/column_types.cc, plugins/column_types.h, plugins/frozen_column.cc, plugins/frozen_column.h, plugins/matrix.cc, plugins/tabular_dataset_column.cc, rest/rest_request_router.cc, sql/cell_value.cc, sql/cell_value.h, sql/expression_value.cc, testing/MLDB-1192-js-procedure-function.js, testing/MLDB-1636-row-column-path.js, testing/MLDB-1710-left-right-rowname.py, testing/MLDB-1742-tabular-dataset-integer-columns.cc, testing/builtin_hash_fct_test.py, testing/cell_value_test.cc, types/date.h, types/testing/date_test.cc
Reduces memory usage for doubles from 12 to 8 bytes/entry, and from timestamps from 12 to 8 or much less if they are integers.
It also puts in place a mechanism that frozen columns can use other frozen columns as part of their implementation.
=> MLDB-2194 double timestamp column format

ext/tensorflow.mk
Avoids needing to modify the source tree when a new version is installed.
=> Detect which version of CUDA and CUDNN are installed (TRIVIAL)

jml-build/functions.mk
Any command line with a semicolon, quote, or parentheses couldn't be saved and hence was re-hashed over and over leading to slow make build times.  This replaces them with underscores and allows this to work, halving the build latency.
=> Fixed slow make due to re-hashing over and over

builtin/python/python_interpreter.cc, python_constraints.txt
Fixes issues with the (very complex) GIL / PyEndInterpreter / PyThreadState_Swap dance that needs to be done to properly end a python interpreter.  Under Python 3.9 some of the deprecated functions that were used segfault.
=> Python interpreter finalization fixes

server/mldb_runner.cc, testing/mldb_mnist_test.cc, testing/mldb_reddit_test.cc
We disable all tests from listening on the internet when starting the mldb_runner processes.
=> Test security: don't allow tests to listen outside of localhost

base/base.mk, base/hash.cc, ext/crypto++, ext/cryptopp.mk, ext/ext.mk, vfs_handlers/aws/aws.cc, vfs_handlers/aws/aws.mk
Not all platforms that MLDB runs on have an accessible way to install a secure version of cryptopp, so instead we vendor it in.
=> Vendored cryptopp (OSX)

builtin/js/js_common.cc, builtin/js/js_value.h
Fixes for the v8 functionality merged earlier that allow it to target a broader range of versions of V8.
=> V8: target a broader set of underlying versions

builtin/filtered_dataset.cc, builtin/joined_dataset.cc, builtin/merged_dataset.cc, builtin/sampled_dataset.cc, builtin/sub_dataset.cc, builtin/transposed_dataset.cc, core/dataset.h, engine/dataset_utils.cc, engine/dataset_utils.h, plugins/behavior/behavior_dataset.cc, plugins/behavior/behavior_domain.cc, plugins/behavior/binary_behavior_dataset.cc, plugins/embedding/embedding.cc, plugins/mongodb/mongo_dataset.cc, plugins/sparse/sparse_matrix_dataset.cc, plugins/sqlite/sqlite_dataset.cc, plugins/tabular/tabular_dataset.cc, sql/expression_value.h, testing/MLDB-1486-embedding-types.js, testing/MLDB-1891-case-in-import.py
MLDB has been developed on platforms where `size_t`, `uint64_t` and `unsigned long long` are the same thing.  This is not the case on OSX.  This patch series fixes the confusion, and modifies the internal MLDB type system to call integral types "i64" and "u64" instead of the C++ names like "long long" which can vary between platforms.
One more step along the way to OSX support.
=> size_t <-> uint64_t confusion

.gitlab-ci.yml, jml-build/to_junit.py
When a test failed, we sometimes crashed the junit script, leading to a hang.  This fixes the hang and ensures that the test suite will eventually finish, turning a timeout on test failure into an explicit test failure.
=> Fix failed test causing junit script to hang

.gitignore, block/memory_region.cc, block/memory_region.h, plugins/tabular/frozen_column.cc, plugins/tabular/frozen_column.h, plugins/tabular/frozen_tables.cc, plugins/tabular/frozen_tables.h, plugins/tabular/tabular.mk, plugins/tabular/tabular_dataset.cc, plugins/tabular/tabular_dataset.h, plugins/tabular/tabular_dataset_chunk.cc, plugins/tabular/tabular_dataset_chunk.h, plugins/tabular/testing/testing.mk, plugins/tabular/testing/transducer_test.cc, plugins/tabular/transducer.cc, plugins/tabular/transducer.h
Many fields in datasets have a combination of a fixed format with some non-varying characters (eg, the UUIDs have "-" characters) and a reduced range of characters (eg, hexadecimal).  This patch detects single-length fields and uses modulo-encoding to pack them into fixed-with integers with all of the entropy.  It reduces (for example) the storage required for hexadecimal IDs by a factor of two.
It's a first step, there is much more that can be done.
=> ID transducer

.gitlab-ci.yml, jml-build/clang.mk, jml-build/functions.mk
Ensures that we won't accidentally introduce regressions.
=> Enable both address and undefined behavior sanitizers in CI/CD
