container_files/assets/www/doc/builtin/procedures/XlsxImporter.md
plugins/plugins.mk
plugins/xlsx_importer.cc
testing/MLDB-1011-excel-import.js
testing/testing.mk

Adds a basic, experimental .xlsx importer, with a basic set of
tests that uses the input files of an external .xlsx -> .csv
converter.

Added Excel .xlsx importer (MLDB-1011)

---

sql/binding_contexts.cc
testing/MLDB-1190_segfault_sqlexpr_jseval.py
testing/testing.mk

fixing the segfault reported by Francois

Mldb 1190 intermittent segfault jseval

---

arch/spinlock.h

Very simple change.  We take the GCC-specific spinlock implementation we had, simplify it and make it use C++11 atomics.

Streamlined and standardized ML::Spinlock (MLDB-1211)

---

plugins/accuracy.cc
plugins/accuracy.h
plugins/classifier.cc
plugins/classifier.h
plugins/experiment_procedure.cc
plugins/experiment_procedure.h
plugins/probabilizer.cc
plugins/sql_config_validator.h
plugins/sql_expression_extractors.h
sql/sql_expression.cc
testing/MLDB-173-multiclass.js
testing/MLDB-174-regression.js
testing/MLDB-198-classifier-weights.js
testing/MLDB-429-assert_fails_for_training.cc
testing/MLDB-565-classifier-details.js
testing/MLDB-573_explain_function_floats.py
testing/MLDB-587-empty-classifier.js
testing/MLDB-59-probabilizer.js
testing/MLDB-592-bs-training-failure.py
testing/MLDB-620-nonexistant-dataset-messages.js
testing/MLDB-654-classifier-function-info.js
testing/MLDB-775_train_with_hashbucket_feat.py
testing/MLDB-779_cant_test_bs_cls.py
testing/MLDB-785-decision-tree-missing.js
testing/MLDB-804-null-accuracy.js
testing/MLDB-896_table_expression_serialised_as_string.cc
testing/MLDB-945-WHEN-in-proc-and-func.py
testing/MLDB-961-glz-categorical.js
testing/mnist_example.js

- modified accuracy to take a score in its testingData expression
- modified accuracy and classifier to take a weight in its input data
- adapted experiment accordingly
- updated test cases

[MLDB-1104] folded score and weight into the sql query

---

server/bound_queries.cc

MLDB-1210 change error message

---

plugins/kmeans.cc
plugins/kmeans.h
testing/MLDB-1043-bucketize-procedure.js

kmeans function has been modified to take its SQL query in a single parameter.

Mldb 1104 export

---

plugins/stats_table_procedure.cc
plugins/stats_table_procedure.h
plugins/tfidf.cc
plugins/tfidf.h
testing/MLDB-1101-tf-idf.py
testing/MLDB-873_stats_table_test.py

I believe this is the last drop at unifying the SQL expressions into a single one.

Mldb 1104 stat tables

---

server/mldb_server.cc

Those statistics are not being used currently and the mechanism in use harms the performance of the systme.

MLDB-1058: stopped logging stats uselessly until performance is improved

---

plugins/stats_table_procedure.cc
types/json_printing.cc

A couple of one line fixes to make clang compilations work again.

clang fixes (MLDB-1264)

---

core/function.cc
plugins/classifier.cc
plugins/json_importer.cc
sql/expression_value.cc
testing/testing.mk

Fixes column names coming out as row..a instead of row.a when flattening.

MLDB-1273 flattening nested rows

---

plugins/nlp.cc
testing/MLDB-1126_stemming.py

Make stemmer function sum the values in cells instead of just counting them.

MLDB-1274 Make stemmer sum cells instead of count them

---

plugins/stats_table_procedure.cc
plugins/stats_table_procedure.h
testing/MLDB-873_stats_table_test.py

[MLDB-1311] fixed the mismatch in the config.

---

builtin/sub_dataset.cc
builtin/sub_dataset.h
container_files/assets/www/doc/builtin/sql/FromExpression.md
container_files/assets/www/doc/builtin/sql/ValueExpression.md
sql/builtin_functions.cc
sql/sql_expression.cc
sql/sql_expression.h
sql/sql_expression_operations.cc
sql/table_expression_operations.cc
sql/table_expression_operations.h
testing/MLDB-1315-row-table-expressions.js
testing/testing.mk
types/string.cc
types/string.h

This allows rows to be used in table expressions, allowing rewriting and filtering of rows and gathering using joins.

MLDB-1315 row as table expression

---

container_files/assets/www/doc/builtin/functions/Fetcher.md
container_files/assets/www/doc/builtin/sql/ValueExpression.md
core/dataset.cc
core/dataset.h
core/function.cc
core/function.h
plugins/fetcher.cc
plugins/json_importer.cc
plugins/plugins.mk
sql/builtin_functions.cc
sql/cell_value.cc
sql/expression_value.cc
sql/expression_value.h
testing/MLDB-1216-fetcher-function.js
testing/MLDB-1266-import_json.py
testing/dataset/json_dataset.json
testing/testing.mk
types/json_parsing.cc
types/json_parsing.h
types/json_parsing_impl.h

Allows us to fetch URLs as part of a query and operate on what is behind them.

MLDB-1216 fetcher function

---

builtin/joined_dataset.cc
builtin/sub_dataset.cc
plugins/json_importer.cc
server/function_contexts.cc
server/function_contexts.h
sql/sql_expression_operations.cc
testing/MLDB-1361_join_on_subselect.py
testing/testing.mk

-Fix issue with accessing columns from an outer Join
-Fix issue with using functions with arguments in Join expression

Mldb 1361 join rowname subselect

---

plugins/sql_functions.cc
testing/MLDBFB-332-transform_input_sum_doesnt_exist_test.py

Fix transform procedure not working when there are aggregators without a group by.

Mldb 1344 aggregator in transform

---

rest/http_rest_endpoint.cc
rest/http_rest_endpoint.h
rest/http_rest_service.cc
rest/http_rest_service.h
rest/rest.mk
rest/rest_service_endpoint.h
rest/service_peer.cc
rest/service_peer.h
server/mldb_runner.cc
server/mldb_server.cc
server/mldb_server.h
utils/log.cc
utils/log.h

- added basic request log to MLDB
- the logging is disable by default and can be enable with a command line option (enable-access-log)
- the logging seems to have a significant impact on the performance - I will investigate that to see if there are low handing fruits

Mldb 1340 access log

---

sql/builtin_functions.cc
testing/MLDB-907-tokenize.py

Allow 'value' argument to be of any atomic type

Mldb 1338 tokenize number

---

jml/utils/profile.h
plugins/nlp.cc
plugins/nlp.h

Also add a couple of useful debug profiling macros I wrote while investigating.

Solve contention in stemming

---

core/dataset.cc
server/bound_queries.cc
server/bound_queries.h
sql/sql_expression.cc
sql/sql_expression.h
testing/testing.mk

The HAVING was already part of the SQL statement and parsed and everything and even in the doc, so I only had to correctly evaluate it in the groupby query.

MLDB-1345 evaluate HAVING expressions

---

container_files/assets/www/doc/builtin/sql/ValueExpression.md
sql/builtin_functions.cc
testing/MLDB-953-normalize.py

Fixes documentation, test cases and implementation for the L0 norm.

Fixed L0 norm (MLDB-1006)

---

server/analytics.cc
server/analytics.h
server/mldb_server.cc
sql/execution_pipeline.cc
sql/execution_pipeline.h
sql/sql_expression.h
sql/table_expression_operations.cc
testing/MLDB-1315-row-table-expressions.js

Adds extra test cases and fixes up issues with the row_dataset() function and the NAMED_COLUMNS mode of sql.query (which is basically its inverse).

Fixed up issues with row dataset literal (MLDB-1374)

---

sql/execution_pipeline.cc
sql/execution_pipeline.h
sql/table_expression_operations.cc
testing/MLDB-1315-row-table-expressions.js

Fixes calling functions within row_dataset()

Further fixes to row_dataset (MLDB-1374)

---

.gitmodules
Makefile
container_files/assets/www/doc/builtin/functions/Fetcher.md
container_files/assets/www/doc/builtin/sql/ValueExpression.md
ext/ext.mk
ext/jpeg.mk
ext/re2.mk
ext/tensorflow.mk
jml-build/functions.mk
mldb.mk
mldb_macros.mk
server/mldb_doc_server.cc
sql/builtin_functions.cc
sql/execution_pipeline_impl.cc
sql/expression_value.cc
sql/expression_value.h
sql/sql_expression.h
sql/table_expression_operations.cc
tensorflow/MLDB-1203-tensorflow-plugin.js
tensorflow/doc/Tensorflow.md
tensorflow/doc/TensorflowGraph.md
tensorflow/mldb_plugin.json
tensorflow/tensorflow.mk
tensorflow/tensorflow_plugin.cc
tensorflow/tensorflow_plugin.h

Allows Tensorflow graphs to be loaded and executed by MLDB.  There are a couple of small cleanups before the code is merged, but this is the vast majority of the functionality.

Added Tensorflow support to MLDB (MLDB-1203)

---

ext/tensorflow.mk

Fixed paths for submodule inclusion of MLDB (TRIVIAL)

---

Building.md
Makefile
container_files/init/ipython_notebook_runner.sh
mldb_base/docker_create_mldb_base.sh
mldb_base/rebuild_pycs.py
python_constraints.txt
python_requirements.txt

- All python deps are upgraded to their latest version.
- A few tweaks were required to match new behaviour.

MLDB-1382 upgrade python deps

---

container_files/assets/www/doc/builtin/procedures/JSONImporter.md
container_files/assets/www/doc/builtin/procedures/MeltProcedure.md
container_files/assets/www/doc/builtin/sql/ValueExpression.md
sql/builtin_functions.cc
testing/MLDB-1266-import_json.py
testing/MLDB-1275_melt_procedure.py

NK will update the doc afterwards.

MLDB-1354 merge unpack_json into parse_json

---

rest/rest_request_params.cc

Allow case-insensitive boolean REST parameters (MLDB-1261)

---

jml-build/functions.mk

One-liner to fix build issues with C targets

C targets create their output directories (MLDB-1416)

---

base/base.mk
base/parallel.cc
base/parallel.h
base/thread_pool.cc
ml/jml/decision_tree_generator.cc
ml/neural/auto_encoder_trainer.cc
ml/neural/discriminative_trainer.cc
ml/tsne/tsne.cc
plugins/sparse_matrix_dataset.cc

Fixes various issues in the new ThreadPool and adds the ability to specify the concurrency level.
Closes MLDB-1423, MLDB-1424, MLDB-1425

MLDB-1423 thread pool improvements

---

sql/builtin_functions.cc
sql/sql_expression.h
sql/sql_expression_operations.cc
testing/MLDB-1235-temporal-aggregators.py
testing/testing.mk

Added a filter parameter to bound function structure to let function decide how to filter their values.  This approach is less encapsulated as it delegates to the callers (e.g FunctionCallWrapper) the work of filtering in the right-way the function arguments before passing them but it has the advantage of being a lot less intrusive (the signature of the BoundFunction exec is kept as-is).

Mldb 1420 filter in function

---

plugins/importtext_procedure.cc
plugins/tabular_dataset.cc
plugins/tabular_dataset.h
testing/MLDB-1428-text-sparse-output.py
testing/testing.mk

Allow text.import procedure to import text with a select expression with an open schema.

Mldb 1428 text sparse output

---

core/dataset.cc
plugins/bucketize_procedure.cc
sql/binding_contexts.cc
sql/builtin_functions.cc
testing/MLDB-1043-bucketize-procedure.js
testing/MLDB-1267-bucketize-ts-test.py
testing/MLDB-605-timestamp-query.js
testing/MLDB-724-time-arithmetic.js
testing/MLDB-906-date-function.py
testing/MLDB-909-simple-WHEN-expression.py
testing/MLDB-927-null-row-output.py
testing/MLDB-945-WHEN-in-proc-and-func.py
testing/MLDB-963-when-in-WHEN.py
testing/MLDBFB-335_when_timestamp_variable_test.py
testing/sql_expression_test.cc

This is only the renaming part of MLDB-1357.

[MLDB-1357] renamed a few time related functions

---

plugins/sparse_matrix_dataset.cc

Fixes the incorrect columnCount

MLDB-1436 sparse.mutable status typo

---

builtin/joined_dataset.cc
builtin/sub_dataset.cc
container_files/public_html/doc/builtin/datasets/TabularDataset.md
core/dataset.h
plugins/tabular_dataset.cc
server/dataset_collection.cc
server/mldb_doc_server.cc
server/static_content_macro.cc

- hid sub and joined datasets
- fixed the documentation of tabular

[MLDB-1439] hid dataset entities and fixed the tabular documentation

---

container_files/init/ipython_notebook_runner.sh
container_files/mldb_nginx_site.conf

Tweaks to the nginx config for error handling in hosted.

MLDB-1455 error pages

---

testing/MLDB-1172_column_expr_fail.py

Ce PR contient le nouveau test (test_column_expr_in_where) ainsi que le refactoring du test existant.

MLDBFB-412 column expr where issue

---

server/bound_queries.cc
server/sql_expression_function_operations.cc
sql/binding_contexts.cc
sql/binding_contexts.h
sql/sql_expression_operations.cc
testing/MLDB-1430-aggregate-bug.py

This changes 3 error messages to be easier to understand.

Mldb 1478 must override error message

---

Makefile
core/dataset.cc
plugins/for_each_line.cc
plugins/for_each_line.h
sql/coord.cc
sql/coord.h
sql/expression_value.cc
sql/expression_value.h
sql/sql_expression_operations.cc
types/json_parsing.cc

A bunch of minor SQL performance improvements.
Includes an interface improvement and minor bug fix for forEachLineBlock.

Mldb 15xx perf improvements

---

sql/execution_pipeline_impl.cc
testing/MLDB-800-nested_sql_query.py

This is to unblock Alexis while waiting for the larger refactoring.

MLDB-1574 check alias in TableLexicalScope::doGetAllColumns

---

sql/join_utils.cc
sql/sql_expression.cc
sql/sql_expression.h
sql/sql_expression_operations.cc
testing/MLDB-1559-transform-method.cc
testing/MLDB-180-basic-join.js
testing/testing.mk

Fix the transform method of most sql expressions and document it.

Mldb 1559 fix transform

---

plugins/sql_functions.cc
testing/MLDB-800-nested_sql_query.py

Conflicts:
testing/MLDB-800-nested_sql_query.py

Fixed double adding of variables in binding (MLDB-1560)

---

sql/sql_expression.cc
testing/MLDB-1597-regression.py
testing/MLDB-895-fuzz-cases.py

Fix precedence problem with BETWEEN.  Created MLDBFB-503 to augment the testing of precedence in SQL expression.

[MLDB-1597] fixed precedence of BETWEEN and IN

---

container_files/public_html/doc/builtin/sql/ValueExpression.md
ml/jml/stump_regress.h
plugins/classifier.cc
plugins/dataset_feature_space.cc
sql/builtin_functions.cc
testing/MLDB-1597-regression.py
testing/MLDB-917_replace_nan_inf.py

Also includes some more functions we can use in the WHERE to fix it.

Improved error message for training regression on inf/NaN (MLDB-1605)

---

plugins/accuracy.cc
testing/MLDB-174-regression.py
testing/MLDB-256_accuracy_accepts_all_cls_modes.py

Fixes r2 score calculation. Prevents us from falling into edge cases with previous method

Mldb 1597 r2

---

testing/MLDBFB-506-stats-tbl-sql-expr.py
testing/testing.mk

This was suppose to outline a bug but merging with master just fixed it. @nicolaskruchten you can decide if it's worth merge it anyway.

[MLDBFB-506] add a test case

---

core/dataset.cc
ml/separation_stats.h
plugins/dataset_feature_space.cc
plugins/importtext_procedure.cc
plugins/tabular_dataset.cc
python_constraints.txt
python_requirements.txt
sql/expression_value.cc
sql/expression_value.h
sql/path.cc
sql/sql_expression_operations.h
types/json_parsing.cc

make compile toolchain=clang now completes

Fix compile errors with clang (MLDB-1623)

---

core/dataset.cc
server/bound_queries.cc
server/bound_queries.h
sql/execution_pipeline_impl.cc
sql/sql_expression.cc
sql/sql_expression.h
sql/sql_expression_operations.h
testing/MLDB-1500-transpose-query.js
testing/MLDB-1597-regression.py
testing/testing.mk

Allow aggregator functions in order by expressions

Mldb 1500 order by aggregators

---

base/testing/thread_pool_test.cc

We put an environnement variable on jenkins to disable those tests.

Mldb 1692 thread pool test

---

ml/jml/glz_classifier_generator.cc

+ set default nb iterations to 1000
it's the default in scikit-learn and normally it will stop before that because of the epsilon stopping criteria anyway

[MLDB-1685] clarify the doc for the L1 regularization in the glz

---

testing/MLDBFB-440_error_on_ds_wo_cols.py

Seems like the issue has already been fixed.

MLDB-1578 activate test

---

builtin/joined_dataset.cc
testing/MLDB-1624-more-join-test.py

Fix row names for cross joins of subqueries in batch executor

Mldb 1673 table name join

---

sql/path.cc
sql/path.h
sql/testing/path_test.cc
testing/MLDB-284-tsne-apply-function.py

Gains back the speed lost from the natural sorting of paths.

Path sorting optimizations (MLDB-1699)

---

testing/generate_test.py

Utilisation
```
%> cd testing
%> python generate_test.py MLDB-123_test_mon_fix.py
```

MLDB-1729 test skeleton generator

---

ext/s2.mk
ml/jml/naive_bayes_generator.h
rest/rest_collection.cc
sql/sql.mk
sql/sql_expression_operations.h

Another round of fixes to make it all compile with clang again.

Clang compilation fixes (TRIVIAL)

---

container_files/public_html/doc/builtin/procedures/Classifier.md
ext/s2.mk
ml/jml/naive_bayes.cc
ml/jml/naive_bayes.h
ml/jml/naive_bayes_generator.h
rest/rest_collection.cc
sql/sql.mk
sql/sql_expression_operations.h
testing/MLDB-1724-naive-bayes.py

This time, with an assert that the algorithm actually does something sensible.
It fixed a bug in serialization and reconstitution of the classifier.
Also had to fix up clang compilation as doing it on a plane (first airborne pull request FTW)!

MLDB-1724 naive bayes (again)

---

container_files/public_html/doc/builtin/Url.md
soa/service/sftp.cc
soa/service/sftp.h

Support sftp MLDB. Le support pour un port spécifique n'est pas inclus.

Mldb 1746 sftp support

---

plugins/json_importer.cc
testing/MLDB-1266-import_json.py

json import select filter

---

ml/jml/classifier.h
ml/jml/feature_set.h
plugins/classifier.cc
testing/MLDB-1724-naive-bayes.py

Fixes classifier.apply assuming that the optimize() function of its classifiers would always work, and then the test-case.
This should make naive bayes officially unborken again.

MLDB-1768 naive bayes categorical

---

plugins/importtext_procedure.cc

Trivial error message improvement to slightly improve usability.

Improved error message for bad UTF-8 encoding (MLDB-1511)

---

testing/MLDB-1503-bad-rowname-error-message.js
testing/testing.mk

Simple testcase to verify fix.

Added testcase to verify fix (MLDB-1503)

---

plugins/importtext_procedure.cc
testing/MLDB-1502-import-text-column-name-confusion.js

The previous PR didn't add the runOnCreation flag, and didn't query the result, and so was a spurious pass.  This fixes the testcase and the underlying issue.  For real this time.

Made test assert on something & actually fixed (MLDB-1502)

---

http/http.mk
http/http_client.cc
http/http_client.h
http/http_client_callbacks.cc
http/http_client_callbacks.h
http/http_client_impl.cc
http/http_client_impl.h
http/http_client_impl_v1.cc
http/http_client_impl_v1.h
http/http_request.cc
http/http_request.h
http/http_socket_handler.cc
http/testing/http_client_bench.cc
http/testing/http_client_online_test.cc
http/testing/http_client_test.cc
http/testing/http_testing.mk
http/testing/test_http_services.cc
http/testing/test_http_services.h
io/event_loop.h
io/io.mk
io/legacy_event_loop.cc
io/legacy_event_loop.h
io/tcp_socket_handler_impl.cc
io/tcp_socket_handler_impl.h
soa/service/runner.cc
soa/service/runner.h
soa/service/testing/runner_test.cc
types/libc_value_descriptions.cc
types/libc_value_descriptions.h
types/types.mk

This PR provides an implementation of HTTPClient from upstream, as a milestone towards MLDBFB-239. The curl-based implementation was chosen as its performance was sufficiently good for S3 and as it is considered to be the most stable one.
Additionally:
* some related classes have been fixed after bugs were revealed
* libc_value_description has been added

Mldbfb 601 http client integration

---

container_files/public_html/doc/builtin/sql/ValueExpression.md
sql/builtin_functions.cc
sql/builtin_http_functions.cc
testing/MLDBFB-573_parse_json.py

We will investigate replacing this flag with a try() function as part of a different ticket

Mldb 1787 ignore errors js parse

---

testing/MLDBFB-239-s3-test.cc
testing/testing.mk

This PR imports the s3_test suite from our private projects. This test covers all the methods from S3Api, directly or not, as well as the s3 vfs handler.

MLDBFB-239: imported s3 testsuite

---

sql/expression_value.cc

Small optimization to reduce allocations in a very heavily used codepath.

Don't create unnecessary paths on forEachAtom (MLDB-1846)

---

server/bound_queries.cc
sql/sql_expression.cc
sql/sql_expression.h
testing/MLDB-1841-distinct-on.py

-Add support for multiple distinct on clauses
-Fix for transformed dataset by fixing the surface which is used for json encoding.

Mldb 1841 distinct on

---

testing/MLDB-1258_nofrom_segfault.py
testing/MLDB-256_accuracy_accepts_all_cls_modes.py
testing/MLDB-878_experiment_proc.py
testing/MLDBFB-506-stats-tbl-sql-expr.py

saving test files under tmp

---

sql/builtin_aggregators.cc
testing/MLDB-1594-aggregator-empty-row.py

Fixed handling of null rows in aggregator on sparse data.

Mldb 1866 aggregator prob

---

core/procedure.h
plugins/bucketize_procedure.cc
plugins/ranking_procedure.cc
plugins/summary_statistics_proc.cc
plugins/templates/procedure.cc.txt

generic output ds share their description string

---

arch/gc_lock.h
base/parse_context.h
ext/jsoncpp/json_value.cpp
ext/s2.mk
ext/sqlite/sqlite3pp.cc
ext/sqlite/sqlite3pp.h
ext/tensorflow.mk
jml/stats/distribution.h
jml/utils/testing/live_counting_obj.h
ml/jml/classifier.cc
ml/jml/judy_array.h
ml/separation_stats.h
ml/svd_utils.cc
ml/tsne/quadtree.h
plugins/lang/js/js_common.cc
rest/rest_service_endpoint.h
rest/testing/rest_collection_stress_test.cc
sql/eval_sql.h
sql/expression_value.cc
sql/expression_value.h
sql/expression_value_conversions.cc
sql/sql.mk
testing/MLDB-1452-like-operator.py
testing/credentials_persistence_test.cc
utils/compact_vector.h
utils/testing/compact_vector_test.cc
vfs_handlers/s3_handlers.cc

make toolchain=gcc6 now compiles and passes all tests

Compilation and tests pass with gcc6 (MLDB-1895)

---

jml-build/functions.mk
mldb_macros.mk

Improvements to macros to allow plugins to include installed directories and binaries

Implemented plugin macros (MLDB-1904)

---

plugins/tsne.cc
plugins/tsne.h

learningRate was added (equivalent of "eta" in ml/tsne/tsne.h)

Added the learningRate field to tsne.train

---

plugins/lang/js/js_common.cc

JS scripts that perform a GC cycle need GC to happen, which is done via this callback.  This implements the missing functionality to allow for the GC to actually happen.

Fixed crashes on long running JS scripts (MLDB-1925)

---

utils/log_fwd.h

Fixed typos in two logging macros.

[MLDB-1918] fixed the logging macros

---

container_files/public_html/doc/builtin/sql/ValueExpression.md
sql/builtin_functions.cc
sql/expression_value.cc
sql/expression_value.h
sql/sql_expression_operations.cc
testing/MLDB-1947-reshape-builtin.py
testing/testing.mk

Useful when dealing with tensors & tensorflow.

MLDB-1947 add shape and reshape builtins

---

sql/expression_value.cc
sql/expression_value.h
tensorflow/doc/Tensorflow.md
tensorflow/tensorflow_plugin.cc

Some incorrect or missing type conversion, found while working on a demo.

small fixes and improvements to tensorflow plugin

---

ext/edlib.mk
ext/ext.mk

@jeremybarnes looks good or makes you sick? ;)

Edlib unit test integration

---

Building.md
builtin/sub_dataset.h
ext/tf_load_kernels.cc
http/http_socket_handler.cc
mongodb/ext/mongodb_ext.mk
mongodb/mongo_common.cc
mongodb/mongo_query.cc
mongodb/mongo_temporary_server.h
sql/expression_value.h
sql/table_expression_operations.cc

The latest instalment in making it possible to develop MLDB on a laptop on a plane...

MLDB-1954 clang

---

sql/path.cc
sql/path.h
sql/sql.mk
sql/testing/path_test.cc
sql/testing/sql_testing.mk
valgrind.supp

Puts path_test under valgrind, and makes it pass with clang as a compiler.

Fixed undefined behaviour in Path (MLDB-1959)

---

container_files/public_html/doc/builtin/procedures/MockProcedure.md
plugins/mock_procedure.cc
plugins/mock_procedure.h
plugins/plugins.mk

Procedure useful to test "things" that require a slow procedure with progress updates.

Mock procedure to fake slow progression

---

core/dataset.h
core/function.h
core/plugin.h
core/procedure.h
plugins/accuracy.cc
plugins/classifier.cc
plugins/continuous_dataset.cc
plugins/dataset_feature_space.cc
plugins/dist_table_procedure.cc
plugins/em.cc
plugins/embedding.cc
plugins/importtext_procedure.cc
plugins/json_importer.cc
plugins/mock_procedure.cc
plugins/summary_statistics_proc.cc
utils/log_fwd.h

@guyd I did a small part so you could tell me if I'm doing it right or wrong before I do more.

Mldb 2018 cerr to logger

---

arch/bit_range_ops.h
arch/testing/bit_range_ops_test.cc
plugins/frozen_column.cc
plugins/frozen_column.h
plugins/lang/python/python_converters.cc
plugins/plugins.mk
plugins/tabular_dataset.cc
plugins/tabular_dataset_chunk.cc
plugins/tabular_dataset_chunk.h
plugins/tabular_dataset_column.cc
plugins/tabular_dataset_column.h
testing/MLDB-1742-tabular-dataset-integer-columns.cc
testing/MLDB-2043_tabular_big_int.py
testing/testing.mk

Fixes problems with Bit_Extractor<uint64_t> causing data corruption in tabular datasets.  Drags along part of a refactoring of the frozen columns.

MLDB-2043 tabular big int

---

plugins/tabular_dataset.cc

columns are outputed at trace level

---

plugins/matrix.cc
plugins/sparse_matrix_dataset.cc

Band-aid patch to fix the immediate test speed problem by adding a missing override and avoiding a very naive computation (iterating the whole dataset on every row to count the number of rows in each column in the row).  This should eventually be fixed at a deeper level by allowing the column selection in `COLUMN EXPR` to be cached when it's constant over the dataset.
Also some minor optimizations to avoid copying and excess lookups in the SVD setup code were added.
It takes the runtime for `MLDB-498-svd-apply-function.js` from 3 minutes to 4 seconds.

Implemented missing getColumnRowCount() in sparse.mutable to fix SVD test speed (MLDB-2028)

---

plugins/csv_export_procedure.cc

fixed the default values that were swapped

---

container_files/init/mldb_logger.py
container_files/init/mldb_logger_utils.py

Also remove it from the 'template file' since it is not templated.

Crank LOGBUFSIZE from 1024 to 8192 lines

---

server/analytics.cc
testing/testing.mk
testing/where-without-dataset.py

evaluate the WHERE even in queries without dataset

---

ext/tensorflow.mk
ext/tf_cuda_handlers.cc
ext/tf_cuda_handlers.h

Use a runtime_error instead of HttpReturnException

Avoid dependency on libhttp in libtensorflow-core

---

core/dataset.cc
plugins/importtext_procedure.cc
plugins/json_importer.cc
plugins/stats_table_procedure.cc
server/bound_queries.cc
utils/progress.h

[MLDB-2122] added constant for progress rate

---

container_files/mldb.conf
tensorflow/tensorflow_plugin.cc

I've added log messages to help debugging the tensorflow plugin.
I've marked `TensorflowOp` with `INTERNAL_ENTITY` to hide it from the documentation.

added log messages to tensorflow plugin

---

container_files/public_html/doc/builtin/sql/ValueExpression.md
sql/builtin_functions.cc
testing/MLDB-2142-prefix-suffix.py
testing/testing.mk

Two simple builtins to remove prefix and suffix from strings.

Mldb 2142 prefix suffix

---

plugins/dist_table_procedure.cc
plugins/dist_table_procedure.h
testing/MLDB-1750-dist-tables.py

Add support for outputDataset in the bagOfWords case for the dist

---

plugins/importtext_procedure.cc
sql/path.h
utils/possibly_dynamic_buffer.h

Nothing to see here, move on... indentation, and making one frequently inlined function always inline.

Trivial changes

---

ml/jml/feature_set.cc
ml/jml/testing/boosting_testing.mk
ml/jml/testing/feature_set_test.cc

Small bug I found while working on multilabel classifications. Multilabel tests will regression-test it.
MDLB-2159

Fix small logic issue with feature_set

---

Building.md

Fixed build instructions (MLDB-2184)

---

container_files/public_html/doc/builtin/WorkingWithRest.md
container_files/public_html/doc/builtin/functions/Fetcher.md
plugins/fetcher.cc

The updated doc prior to releasing.

doc update

---

plugins/classifier.cc
testing/MLDB-2143-classifier-utf8.py
testing/MLDB-2188-label_feature_validation.py
testing/MLDB-945-WHEN-in-proc-and-func.py
testing/test_classifier_test_proc.py
testing/testing.mk

Validate that no column is used as both label and feature in classifier.

MLDB-2188 Classifier label validation

---

ml/jml/fasttext_classifier.cc
ml/jml/fasttext_classifier.h
ml/jml/onevsall.cc
ml/jml/onevsall.h
testing/fasttext_test.py
testing/multilabel-classifier-test.py

Make one-vs-all multilabel support classifier.explain

Mldb 2178 multilabel explain

---

ext/azure-storage-cpp.mk
ext/casablanca.mk
ext/s2.mk
ext/tensorflow.mk
jml-build/functions.mk
jml-build/gcc.mk
jml-build/gcc5.mk
jml/stats/distribution_ops.h
ml/jml/memusage.h
ml/neural/dense_layer_impl.h
ml/neural/parameters_impl.h
ml/tsne/quadtree.h
plugins/behavior/behavior_utils.cc
plugins/lang/js/mldb_js_plugin.mk
plugins/sqlite_dataset.cc
sql/cell_value.cc
sql/path.cc
sql/path.h
sql/sql_expression.cc
sql/testing/path_order_test.cc
sql/testing/path_test.cc
sql/testing/sql_testing.mk
testing/MLDB-1395-error-message-file-doesnt-exist.js
testing/MLDB-2166_mime_type.py
utils/compact_vector.h
utils/interned_string.h
utils/testing/compact_vector_test.cc
valgrind.supp

This series of commits allows MLDB to be built and tests to pass on either Ubuntu 14.04 or Ubuntu 16.04.
It has been verified on both OSs.

Ubuntu 1604

---

ext/s2.mk
server/plugin_resource.cc
testing/mldb_python_plugin_test.cc

Plugins now work on top of NFS (a somewhat hacky fix).

Plugins on NFS

---

vfs/fs_utils.cc
vfs/fs_utils.h
vfs/http_streambuf.cc

Adds content-type to the FSInfo structure so it can be picked up from object types that support it (HTTP)

Fetcher info, metadata, contentType improvements

---

builtin/js/js_function.cc
testing/MLDB-723-jseval-exceptions.js
testing/MLDBFB-458_jseval_exception_message.py
testing/testing.mk

Acts as a demo more than a test.

MLDBFB-458_jseval_error_msg_clarity

---

ext/libarchive-config-Darwin-x86_64.h
ext/libarchive.mk

Update vendored libarchive to version 3.5.1

Libarchive 3.5.1

---

plugins/sqlite/sqlite_dataset.cc

We told sqlite that we would keep the strings around for it, and then we didn't.

Fixed string lifetimes for sqlite query argument binding

---

plugins/jml/jml/early_stopping_generator.cc
plugins/tensorflow/MLDB-1203-tensorflow-plugin.js
testing/MLDB-1266-import_json.py
testing/MLDB-565-classifier-details.js
testing/MLDB-574-sqlite-backend.js
testing/MLDB-59-probabilizer.js
testing/MLDB-785-decision-tree-missing.js
testing/cell_value_test.cc
testing/embedding_dataset_test.cc
testing/fetcher-function.py
testing/mldb_py_runner/mldb_py_runner.py
testing/python_cell_converter_test_support.cc
testing/python_converters_test_support.cc

Improves robustness of the test suite to not depend on random number generation order or other non-fixed
behavior that causes tests to fail on diverse platforms.

Remove test suite assumptions

---

plugins/textual/importtext_procedure.cc

Ensure that the line number and file containing a syntax error is available when text importation fails.

More context in error message when import text fails

---

Makefile
ext/googleurl/base/string16.cc
ext/googleurl/googleurl.mk
ext/libarchive.mk
ext/libgit2.mk
ext/s2.mk
jml-build/clang.mk
jml-build/functions.mk
jml-build/gcc10.mk
jml-build/os/Darwin.mk
jml-build/os/Linux.mk
jml-build/os/os.mk
jml-build/print-line-counts.awk
jml-build/print-timing.awk
jml-build/python.mk
mldb_macros.mk
plugins/embedding/embedding.h
plugins/html/ext/parserutils.mk
utils/interned_string.h

Parameterizes the parts of the build system that are Linux-specific to allow Darwin equivalents to be used.  Adds a few neat features like preprocessed line counts to identify files that include too much code.

Osx build system support

---

Building-OSX.md

Update build instructions for OSX (they have been tested).

OSX build instructions
